version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      #- KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka-connect:
    image: 'kafkaconnect:lastest'
    environment:
      - AWS_ACCESS_KEY_ID=[AWS_ACCESS_KEY_ID]
      - AWS_SECRET_KEY=[AWS_SECRET_KEY]
      - AWS_SECRET_ACCESS_KEY=[AWS_SECRET_ACCESS_KEY]
    depends_on:
      - kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local